# ---------------------------------------------------------------------------
# Merge Command: /file:merge
#
# Description:
#   Merge multiple files or directories into a single output file
#   Useful for combining related content from different files
#
# Usage:
#   /file:merge @source_files into @destination_file
#   Examples: 
#     /file:merge @file1.md @file2.md into @combined-report.md
#     /file:merge @folder into @consolidated-document.md
#     /file:merge @analysis1.md @analysis2.md into @report-[date].md
# ---------------------------------------------------------------------------

name = "file:merge"
description = "Merge specified files or directories together into a single file"

prompt = """
You are a file management assistant. Your task is to merge multiple files or directories into a single output file.

## Merge Instructions
Your merge instructions are:
{{args}}

If you **do not understand** or **cannot complete** the **Merge Instructions**, explain why not, then **hard stop**.

## Date and Time Instructions:
The **CURRENT_DATE** is `date`. The **FN_DATE** is the date in YYYYMMDD format; it is a file-name friendly version of {CURRENT_DATE}. 
The **FN_TIME** is the time in HHMMSS format; is a file-name friendly version of {CURRENT_DATE}.

## File Merging Process:
1. Parse the merge command to identify source files/directories and destination file
2. Check if the destination filename contains placeholders:
   - Replace [date] placeholder with {FN_DATE}
   - Replace [time] placeholder with {FN_TIME}
3. Read and collect content from all specified source files
4. For directories, read all files within the directory
5. Combine all content with appropriate separators and headers
6. Write the merged content to the destination file
7. Provide confirmation of the merge operation

## Content Organization:
- Add clear section headers for each source file
- Include file paths as headers for context
- Separate content from different files with clear dividers
- Preserve original formatting where possible
- Add metadata like merge timestamp and source file list

## File Handling:
- If the destination filename doesn't have an extension, suggest adding .md or .txt
- If the destination file already exists, ask for confirmation before overwriting
- Create any necessary parent directories if needed
- Handle special characters in filenames appropriately
- Skip binary files and warn about them

## Implementation:
Use your file reading and writing capabilities to:
1. Read content from each source file specified
2. Organize the content with clear section headers
3. Write the combined content to the destination file
4. Provide detailed confirmation of what was merged

## Response Format:
After merging files, provide:
- Confirmation message with full destination file path
- List of source files that were merged
- Brief summary of content organization
- File size information if available
- Any warnings about skipped files

Example workflow:
1. User specifies: /file:merge @file1.md @file2.md into @combined-[date].md
2. Replace [date] with current date if present
3. Read content from file1.md and file2.md
4. Combine content with headers and separators
5. Write merged content to combined-YYYYMMDD.md
6. Confirm the merge operation with details
"""

[[examples]]
user = "/file:merge @analysis1.md @analysis2.md into @combined-report.md"
assistant = "I'll merge the contents of analysis1.md and analysis2.md into a single combined-report.md file.\n\nReading source files:\n- analysis1.md: ✅ Read (2.1 KB)\n- analysis2.md: ✅ Read (1.8 KB)\n\nMerging content with section headers and organizing the combined document...\n\n✅ Successfully merged 2 files into combined-report.md\n📄 Total merged content: 4.2 KB\n📁 Location: $(pwd)/combined-report.md\n\nThe merged file includes:\n- Header with merge timestamp and source file list\n- Section 1: Content from analysis1.md\n- Section 2: Content from analysis2.md\n- Preserved original formatting and structure"

[[examples]]
user = "/file:merge @docs into @consolidated-docs.md"
assistant = "I'll merge all files from the docs directory into a single consolidated document.\n\nScanning docs directory:\n- Found 5 markdown files\n- Skipping 1 binary file (image.png)\n\nReading and merging:\n- docs/readme.md: ✅ Read (1.5 KB)\n- docs/setup.md: ✅ Read (2.3 KB)\n- docs/api.md: ✅ Read (3.1 KB)\n- docs/examples.md: ✅ Read (1.9 KB)\n- docs/troubleshooting.md: ✅ Read (1.2 KB)\n\n✅ Successfully merged 5 files into consolidated-docs.md\n📄 Total merged content: 10.0 KB\n📁 Location: $(pwd)/consolidated-docs.md\n⚠️ Skipped 1 binary file\n\nThe consolidated document includes all documentation with clear section separators."

[[examples]]
user = "/file:merge @report1.md @report2.md into @summary-[date].md"
assistant = "I'll merge the reports into a date-stamped summary file.\n\nDetected [date] placeholder - replacing with current date: 20240115\nDestination file: summary-20240115.md\n\nReading source files:\n- report1.md: ✅ Read (3.2 KB)\n- report2.md: ✅ Read (2.8 KB)\n\nMerging content with timestamps and source attribution...\n\n✅ Successfully merged 2 files into summary-20240115.md\n📄 Total merged content: 6.3 KB\n📁 Location: $(pwd)/summary-20240115.md\n🕒 Merge completed at: 2024-01-15 14:30:45\n\nThe summary includes both reports with clear section headers and merge metadata."